#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : flmsg
Version  : 4.0.22
Release  : 23
URL      : https://sourceforge.net/projects/fldigi/files/flmsg/flmsg-4.0.22.tar.gz
Source0  : https://sourceforge.net/projects/fldigi/files/flmsg/flmsg-4.0.22.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: flmsg-bin = %{version}-%{release}
Requires: flmsg-data = %{version}-%{release}
Requires: flmsg-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : fltk-dev
BuildRequires : fontconfig-dev
BuildRequires : libXcursor-dev
BuildRequires : libXft-dev
BuildRequires : libXrender-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
flmsg is a editor / file management tool for ics213 forms which form the
basis for emergency communications data transfers.

%package bin
Summary: bin components for the flmsg package.
Group: Binaries
Requires: flmsg-data = %{version}-%{release}
Requires: flmsg-license = %{version}-%{release}

%description bin
bin components for the flmsg package.


%package data
Summary: data components for the flmsg package.
Group: Data

%description data
data components for the flmsg package.


%package license
Summary: license components for the flmsg package.
Group: Default

%description license
license components for the flmsg package.


%prep
%setup -q -n flmsg-4.0.22
cd %{_builddir}/flmsg-4.0.22
pushd ..
cp -a flmsg-4.0.22 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687790523
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1687790523
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flmsg
cp %{_builddir}/flmsg-%{version}/COPYING %{buildroot}/usr/share/package-licenses/flmsg/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/flmsg
/usr/bin/flmsg

%files data
%defattr(-,root,root,-)
/usr/share/applications/flmsg.desktop
/usr/share/pixmaps/flmsg.xpm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flmsg/8624bcdae55baeef00cd11d5dfcfa60f68710a02
