#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flmsg
Version  : 4.0.17
Release  : 19
URL      : https://sourceforge.net/projects/fldigi/files/flmsg/flmsg-4.0.17.tar.gz
Source0  : https://sourceforge.net/projects/fldigi/files/flmsg/flmsg-4.0.17.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: flmsg-bin = %{version}-%{release}
Requires: flmsg-data = %{version}-%{release}
Requires: flmsg-license = %{version}-%{release}
BuildRequires : compat-gcc-10-dev
BuildRequires : fltk-dev
BuildRequires : fontconfig-dev
BuildRequires : libXcursor-dev
BuildRequires : libXft-dev
BuildRequires : libXrender-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev

%description
flmsg is a editor / file management tool for ics213 forms which form the
basis for emergency communications data transfers.

%package bin
Summary: bin components for the flmsg package.
Group: Binaries
Requires: flmsg-data = %{version}-%{release}
Requires: flmsg-license = %{version}-%{release}

%description bin
bin components for the flmsg package.


%package data
Summary: data components for the flmsg package.
Group: Data

%description data
data components for the flmsg package.


%package license
Summary: license components for the flmsg package.
Group: Default

%description license
license components for the flmsg package.


%prep
%setup -q -n flmsg-4.0.17
cd %{_builddir}/flmsg-4.0.17

%build
## build_prepend content
export CC=gcc-10
export CXX=g++-10
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622049967
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1622049967
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flmsg
cp %{_builddir}/flmsg-4.0.17/COPYING %{buildroot}/usr/share/package-licenses/flmsg/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flmsg

%files data
%defattr(-,root,root,-)
/usr/share/applications/flmsg.desktop
/usr/share/pixmaps/flmsg.xpm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flmsg/8624bcdae55baeef00cd11d5dfcfa60f68710a02
